services:
  kafka:
    image: apache/kafka:4.0.0
    container_name: kafka
    ports:
      - "9092:9092"
    volumes:
      - "./kafka/data:/tmp/kraft-combined-logs/"
      - "./kafka/logs:/opt/kafka/logs/"