spring:
  application:
    name: spring-kafka-poc

  kafka:
    bootstrap-servers: 127.0.0.1:9092

  datasource:
    url: jdbc:h2:mem:kafka-poc
    username: sa
    password:
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 18080